name: day_15
description: Flutter Summer Camp — Day 15 (Intro Riverpod) solution.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true
